### ISSUE TITLE
Infer on Demo data

### ISSUE THREAD

**Issue by Greatsjk** [SiyuanHuang95/ManipVQA#7]
Thanks for your great works. When I try `eval_7B_infer.sh` and use demo_data as dataset, I occurred the error as follow. What should I do? Thank you! 
`Traceback (most recent call last):
  File "/home/kale/workspace/202409/ManipVQA/accessory/eval_manip_7B_single_gpu.py", line 316, in <module>
    results = model.generate(_prompt, image, max_gen_len=max_gen_len, temperature=gen_t, top_p=top_p)
  File "/home/kale/.conda/envs/accessory/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/kale/workspace/202409/ManipVQA/accessory/model/meta.py", line 785, in generate
    logits = self.llma.forward_inference(
  File "/home/kale/.conda/envs/accessory/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/kale/workspace/202409/ManipVQA/accessory/model/meta.py", line 326, in forward_inference
    l_image_tokens: List = self.encode_image(image)
  File "/home/kale/workspace/202409/ManipVQA/accessory/model/meta.py", line 172, in encode_image
    local_512 = torch.stack([local_image_512] + local_parts_512, dim=1)
RuntimeError: stack expects each tensor to be equal size, but got [2, 3, 512, 512] at entry 0 and [2, 3, 224, 224] at entry 1`

**Comment by Greatsjk** [comment]
I have figured out what the problem is, thanks for this great work again.

**Comment by YANGxinyu418** [comment]
> eval_manip_7B_single_gpu.py
Hello, I also encountered this problem when running the eval_manip_7B_single_gpu.py file, how did you solve it? Looking forward to hearing from you
